"""Stream a generated review CSV into the collaboration platform in bounded batches."""

from __future__ import annotations

import argparse
import csv
import json
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Iterable, Iterator
from pathlib import Path
from typing import Any

MAX_BATCH = 500


class Client:
    def __init__(self, base_url: str) -> None:
        self.base_url = base_url.rstrip("/")
        self.token = ""

    def request(self, method: str, path: str, payload: Any | None = None) -> Any:
        data = None if payload is None else json.dumps(payload).encode("utf-8")
        headers = {"Content-Type": "application/json"}
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        request = urllib.request.Request(self.base_url + path, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=90) as response:
                body = response.read()
                return None if not body else json.loads(body)
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"{method} {path} failed: HTTP {exc.code} {detail}") from exc

    def login(self, username: str, password: str) -> None:
        response = self.request("POST", "/api/auth/login", {"username": username, "password": password})
        self.token = response["accessToken"]


def batches(rows: Iterable[dict[str, Any]], size: int) -> Iterator[list[dict[str, Any]]]:
    batch: list[dict[str, Any]] = []
    for row in rows:
        batch.append(row)
        if len(batch) == size:
            yield batch
            batch = []
    if batch:
        yield batch


def task_rows(queue: Path) -> Iterator[dict[str, Any]]:
    with queue.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {
            "candidate_id",
            "split",
            "image_name",
            "class_name",
            "conf",
            "case_code",
            "recommended_action",
            "visual_file",
        }
        missing = required.difference(reader.fieldnames or ())
        if missing:
            raise ValueError(f"review CSV is missing columns: {', '.join(sorted(missing))}")
        for row in reader:
            if not row["candidate_id"].strip():
                continue
            yield {
                "candidateId": row["candidate_id"].strip(),
                "split": row["split"].strip(),
                "imageName": row["image_name"].strip(),
                "className": row["class_name"].strip(),
                "confidence": float(row["conf"]),
                "caseCode": row["case_code"].strip(),
                "recommendedAction": row["recommended_action"].strip(),
                "visualFile": row["visual_file"].replace("\\", "/").strip(),
            }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("queue", type=Path, help="review_queue.csv generated by review-build")
    parser.add_argument("--base-url", default="http://localhost:8088")
    parser.add_argument("--username", required=True)
    parser.add_argument("--password", required=True)
    parser.add_argument("--project-id", type=int)
    parser.add_argument("--project-name", default="Multi-Teacher review")
    parser.add_argument("--review-root", default="/review-data", help="path visible inside the backend container")
    parser.add_argument("--description", default="Imported by platform/tools/import_review_queue.py")
    parser.add_argument("--batch-size", type=int, default=MAX_BATCH)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    queue = args.queue.expanduser().resolve()
    if not queue.is_file():
        raise FileNotFoundError(queue)
    if not 1 <= args.batch_size <= MAX_BATCH:
        raise ValueError(f"--batch-size must be between 1 and {MAX_BATCH}")

    if args.dry_run:
        count = sum(1 for _ in task_rows(queue))
        print(f"validated {count} rows from {queue}")
        return 0

    client = Client(args.base_url)
    client.login(args.username, args.password)
    project_id = args.project_id
    if project_id is None:
        project = client.request("POST", "/api/projects", {
            "name": args.project_name,
            "description": args.description,
            "reviewRoot": args.review_root,
        })
        project_id = int(project["id"])
        print(f"created project {project_id}: {project['name']}")

    received = created = skipped = 0
    for index, batch in enumerate(batches(task_rows(queue), args.batch_size), start=1):
        result = client.request("POST", f"/api/projects/{project_id}/tasks:batch", batch)
        received += int(result["received"])
        created += int(result["created"])
        skipped += int(result["skippedExisting"])
        print(f"batch {index}: received={received} created={created} skipped={skipped}", flush=True)
    print(json.dumps({"project_id": project_id, "received": received, "created": created, "skipped": skipped}))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc
